export const EMOTES = {
  nopeanBlush: document.getElementById("nopeanBlush"),
  nopeanBrian: document.getElementById("nopeanBrian"),
  nopeanCashewevil: document.getElementById("nopeanCashewevil"),
  nopeanParkour: document.getElementById("nopeanParkour"),
  nopeanRambo: document.getElementById("nopeanRambo"),
  nopeanSad: document.getElementById("nopeanSad"),
  nopeanYayawoo: document.getElementById("nopeanYayawoo"),
  nopeanZoomereyes: document.getElementById("nopeanZoomereyes"),
  nopeanPeanut: document.getElementById("nopeanPeanut"),
  nopeanLove: document.getElementById("nopeanLove"),
  nopeanBigbrain: document.getElementById("nopeanBigbrain"),
  nopeanSargeSmile: document.getElementById("nopeanSargeSmile"),
  nopeanLol: document.getElementById("nopeanLol"),
};
